GGEN(fundamental, exit)
TGEN(fundamental, add, uint32)
TGEN(fundamental, add, int32)
BGEN(fundamental, load, 8)
BGEN(fundamental, load, 16)
BGEN(fundamental, load, 32)
BGEN(fundamental, load, 64)
BGEN(fundamental, store, 8)
BGEN(fundamental, store, 16)
BGEN(fundamental, store, 32)
BGEN(fundamental, store, 64)
BGEN(fundamental, equal_condition, 8)
BGEN(fundamental, equal_condition, 16)
BGEN(fundamental, equal_condition, 32)
BGEN(fundamental, equal_condition, 64)

TGEN(fundamental, left_angle_condition, int8)
TGEN(fundamental, left_angle_condition, int32)
TGEN(fundamental, left_angle_condition, int16)
TGEN(fundamental, left_angle_condition, int64)
TGEN(fundamental, left_angle_condition, uint8)
TGEN(fundamental, left_angle_condition, uint32)
TGEN(fundamental, left_angle_condition, uint16)
TGEN(fundamental, left_angle_condition, uint64)
TGEN(fundamental, left_angle_condition, float)
TGEN(fundamental, left_angle_condition, double)

TGEN(fundamental, scan_from_prompt_per_primitive, int8)
TGEN(fundamental, scan_from_prompt_per_primitive, int16)
TGEN(fundamental, scan_from_prompt_per_primitive, int32)
TGEN(fundamental, scan_from_prompt_per_primitive, int64)
TGEN(fundamental, scan_from_prompt_per_primitive, uint8)
TGEN(fundamental, scan_from_prompt_per_primitive, uint16)
TGEN(fundamental, scan_from_prompt_per_primitive, uint32)
TGEN(fundamental, scan_from_prompt_per_primitive, uint64)
TGEN(fundamental, scan_from_prompt_per_primitive, float)
TGEN(fundamental, scan_from_prompt_per_primitive, double)

TGEN(fundamental, print_to_prompt_per_primitive, char)
TGEN(fundamental, print_to_prompt_per_primitive, int8)
TGEN(fundamental, print_to_prompt_per_primitive, int16)
TGEN(fundamental, print_to_prompt_per_primitive, int32)
TGEN(fundamental, print_to_prompt_per_primitive, int64)
TGEN(fundamental, print_to_prompt_per_primitive, uint8)
TGEN(fundamental, print_to_prompt_per_primitive, uint16)
TGEN(fundamental, print_to_prompt_per_primitive, uint32)
TGEN(fundamental, print_to_prompt_per_primitive, uint64)
TGEN(fundamental, print_to_prompt_per_primitive, float)
TGEN(fundamental, print_to_prompt_per_primitive, double)

BGEN(fundamental, constant_mov_to_reg, 8)
BGEN(fundamental, constant_mov_to_reg, 16)
BGEN(fundamental, constant_mov_to_reg, 32)
BGEN(fundamental, constant_mov_to_reg, 64)

BGEN(fundamental, variable_mov_to_reg, 8)
BGEN(fundamental, variable_mov_to_reg, 16)
BGEN(fundamental, variable_mov_to_reg, 32)
BGEN(fundamental, variable_mov_to_reg, 64)

BGEN(fundamental, constant_mov_to_mem, 8)
BGEN(fundamental, constant_mov_to_mem, 16)
BGEN(fundamental, constant_mov_to_mem, 32)
BGEN(fundamental, constant_mov_to_mem, 64)
