GGEN(fundamental, exit)
TGEN(fundamental, add, uint32)
TGEN(fundamental, add, int32)
BGEN(fundamental, load, 8)
BGEN(fundamental, load, 16)
BGEN(fundamental, load, 32)
BGEN(fundamental, load, 64)
BGEN(fundamental, store, 8)
BGEN(fundamental, store, 16)
BGEN(fundamental, store, 32)
BGEN(fundamental, store, 64)
BGEN(fundamental, equal_condition, 8)
BGEN(fundamental, equal_condition, 16)
BGEN(fundamental, equal_condition, 32)
BGEN(fundamental, equal_condition, 64)
